version: "3.9"
services:

  dynamicdns-provider:
    build:
      context: ../../providers/dynamicdns
    ports:
      - "8000:80"

  nginx:
    build:
      context: nginx

  tacodns-adapter:
    build:
      context: ../../adapter
    environment:
      HTTP_ENDPOINT: http://nginx
    ports:
      - "53:53/tcp"
      - "53:53/udp"
