version: "3.9"
services:

  nginx:
    build:
      context: nginx
    volumes:
      - ./zones:/zones

  tacodns-adapter:
    build:
      context: ../../adapter
    environment:
      HTTP_ENDPOINT: http://nginx
    ports:
      - "53:53/tcp"
      - "53:53/udp"
