version: "3.9"
services:

  ens-provider:
    build:
      context: ../../providers/ens

  tacodns-gateway:
    build:
      context: ../../gateway
    environment:
      HTTP_ENDPOINT: http://ens-provider
    ports:
      - "53:53/tcp"
      - "53:53/udp"
